
// This file has been generated by the GUI designer. Do not modify.
namespace MoodImage
{
	public partial class Window
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Image displayImage;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView info;

		private global::Gtk.Image plotImage;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MoodImage.Window
			this.Name = "MoodImage.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MoodImage.Window.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.displayImage = new global::Gtk.Image();
			this.displayImage.Name = "displayImage";
			this.vbox2.Add(this.displayImage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.displayImage]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.info = new global::Gtk.TextView();
			this.info.CanFocus = true;
			this.info.Name = "info";
			this.info.Editable = false;
			this.info.CursorVisible = false;
			this.GtkScrolledWindow.Add(this.info);
			this.alignment1.Add(this.GtkScrolledWindow);
			this.vbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.alignment1]));
			w5.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.plotImage = new global::Gtk.Image();
			this.plotImage.Name = "plotImage";
			this.vbox1.Add(this.plotImage);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.plotImage]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 572;
			this.Show();
		}
	}
}
