
// This file has been generated by the GUI designer. Do not modify.
namespace MoodImage
{
	public partial class Window
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView info;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MoodImage.Window
			this.Name = "MoodImage.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MoodImage.Window.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.info = new global::Gtk.TextView();
			this.info.Buffer.Text = "this is an example";
			this.info.CanFocus = true;
			this.info.Name = "info";
			this.GtkScrolledWindow.Add(this.info);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
